# Name of website
title: Toolit(ML)

theme: jekyll-theme-cayman

# Your name to show in the footer
author: Kareem Soliman

defaults:
  -
scope:
path: "" # an empty string here means all files in the project
type: "posts"
values:
is_post: true
